import { useRef, useState } from 'react'
import {
  FileText, Download, Share2, ChevronLeft,
  Calendar, IndianRupee, TrendingUp, Globe2,
  ArrowRight, Loader2, ShieldCheck
} from 'lucide-react'
import { toast } from 'sonner'
import type { ROIResult, StudentProfile, DataVerification } from '../types'

interface Props {
  result:       ROIResult
  profile:      StudentProfile
  verification: DataVerification | null
  onBack:       () => void
}

export default function ParentReport({ result: r, profile: p, verification, onBack }: Props) {
  const reportRef  = useRef<HTMLDivElement>(null)
  const [pdfLoading, setPdfLoading] = useState(false)

  const metrics = [
    { label: 'Monthly EMI',     value: r.emi_monthly,              icon: IndianRupee },
    { label: 'Starting salary', value: r.salary_yr1,               icon: TrendingUp  },
    { label: 'Loan breakeven',  value: `Month ${r.breakeven_month}`, icon: Calendar  },
    { label: 'PR probability',  value: `${r.pr_probability}%`,     icon: Globe2      },
  ]

  // ── Working PDF download using jsPDF ──────────────────────
  const downloadPDF = async () => {
    setPdfLoading(true)
    toast.info('Generating PDF…')
    try {
      // Dynamic import so bundle stays light for users who never click
      const [{ default: jsPDF }, { default: html2canvas }] = await Promise.all([
        import('jspdf'),
        import('html2canvas'),
      ])

      const el = reportRef.current
      if (!el) throw new Error('Report element not found')

      // Render the report div to a canvas at 2× resolution
      const canvas = await html2canvas(el, {
        scale: 2,
        useCORS: true,
        backgroundColor: '#ffffff',
        logging: false,
      })

      const imgData = canvas.toDataURL('image/png')
      const pdf     = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })

      const pageW  = pdf.internal.pageSize.getWidth()
      const pageH  = pdf.internal.pageSize.getHeight()
      const margin = 10

      const imgW = pageW - margin * 2
      const imgH = (canvas.height * imgW) / canvas.width

      // If content is taller than one page, split across pages
      let yOffset = 0
      let remainH = imgH

      while (remainH > 0) {
        const sliceH = Math.min(remainH, pageH - margin * 2)
        const srcY   = yOffset * (canvas.height / imgH)
        const srcH   = sliceH * (canvas.height / imgH)

        // Create a temp canvas for this slice
        const slice     = document.createElement('canvas')
        slice.width     = canvas.width
        slice.height    = srcH
        const ctx = slice.getContext('2d')!
        ctx.drawImage(canvas, 0, srcY, canvas.width, srcH, 0, 0, canvas.width, srcH)

        if (yOffset > 0) pdf.addPage()
        pdf.addImage(slice.toDataURL('image/png'), 'PNG', margin, margin, imgW, sliceH)

        yOffset  += sliceH
        remainH  -= sliceH
      }

      // Metadata
      pdf.setProperties({
        title:   `${p.name} — ROI Oracle Report`,
        subject: `Study Abroad ROI — ${p.program}, ${p.country}`,
        author:  'ROI Oracle by Leap Scholar',
        creator: 'ROI Oracle — Leap AI Hackathon 2026',
      })

      pdf.save(`ROI-Oracle-${p.name.replace(/ /g, '-')}-${p.country}.pdf`)
      toast.success('PDF downloaded!')
    } catch (err) {
      console.error(err)
      toast.error('PDF generation failed. Try again.')
    } finally {
      setPdfLoading(false)
    }
  }

  const shareWhatsApp = () => {
    const text = encodeURIComponent(
      `📊 *ROI Oracle — Study Abroad Report*\n\n` +
      `Student: ${p.name}\n` +
      `Program: ${p.program}\n` +
      `Country: ${p.country}\n\n` +
      `💰 Starting salary: ${r.salary_yr1}\n` +
      `📅 Loan breakeven: Month ${r.breakeven_month}\n` +
      `🏠 PR probability: ${r.pr_probability}%\n` +
      `📈 Net ROI (Year 3): ${r.net_roi_yr3}\n\n` +
      `Generated by ROI Oracle — Leap Scholar`
    )
    window.open(`https://wa.me/?text=${text}`, '_blank')
    toast.success('Opening WhatsApp…')
  }

  return (
    <div className="space-y-4 animate-slide-up">
      <div>
        <h2 className="text-xl font-extrabold text-navy-900 tracking-tight mb-1">Parent-ready report</h2>
        <p className="text-sm text-slate-500">Plain language. No jargon. Download as PDF or share on WhatsApp.</p>
      </div>

      {/* ── Printable report area ── */}
      <div ref={reportRef} className="bg-white border border-slate-200 rounded-3xl overflow-hidden shadow-card-md">
        {/* Report header */}
        <div className="bg-navy-900 p-6 relative overflow-hidden">
          <div className="absolute top-0 right-0 w-36 h-36 bg-brand-orange/20 rounded-full -translate-y-1/2 translate-x-1/2" />
          <div className="absolute bottom-0 left-1/4 w-24 h-24 bg-brand-green/10 rounded-full translate-y-1/2" />
          <div className="relative z-10 flex items-start gap-3">
            <div className="w-10 h-10 bg-brand-orange rounded-xl flex items-center justify-center flex-shrink-0 mt-0.5">
              <FileText size={18} color="white" />
            </div>
            <div>
              <div className="text-base font-extrabold text-white mb-0.5">
                {p.name} — Study abroad ROI analysis
              </div>
              <div className="text-xs text-white/50">
                {p.program} · {p.country} · ₹{p.loanLakhs}L loan · ROI Oracle by Leap Scholar
              </div>
            </div>
          </div>
        </div>

        <div className="p-6 space-y-5">
          {/* Bottom line */}
          <div>
            <div className="section-label mt-0">The bottom line</div>
            <div className="bg-brand-green-light border border-green-200 rounded-2xl p-4 text-sm text-green-800 leading-relaxed font-medium">
              {r.parent_highlight}
            </div>
          </div>

          {/* Key metrics grid */}
          <div className="grid grid-cols-2 gap-3">
            {metrics.map(({ label, value, icon: Icon }) => (
              <div key={label} className="bg-slate-50 border border-slate-200 rounded-xl p-3.5">
                <div className="flex items-center gap-1.5 text-[10px] font-bold text-slate-400 uppercase tracking-widest mb-2">
                  <Icon size={11} />{label}
                </div>
                <div className="text-base font-extrabold text-navy-900">{value}</div>
              </div>
            ))}
          </div>

          {/* Full analysis */}
          <div>
            <div className="section-label">Full analysis</div>
            <p className="text-sm text-slate-500 leading-relaxed">{r.narrative}</p>
          </div>

          {/* Data sources summary */}
          {verification && (
            <div className="bg-blue-50 border border-blue-200 rounded-2xl p-4">
              <div className="flex items-center gap-2 mb-2.5">
                <ShieldCheck size={14} className="text-blue-500" />
                <div className="text-xs font-bold text-blue-700 uppercase tracking-wide">
                  Data sources — {verification.overallConfidence}% confidence
                </div>
              </div>
              <div className="grid grid-cols-1 gap-1.5">
                {verification.sources.map(s => (
                  <div key={s.metric} className="flex items-baseline justify-between text-xs">
                    <span className="text-blue-600 font-semibold">{s.metric}:</span>
                    <span className="text-blue-800 font-bold ml-2 text-right">
                      {s.value}
                      <span className="text-blue-500 font-normal ml-1">[{s.apiName}]</span>
                    </span>
                  </div>
                ))}
              </div>
            </div>
          )}

          <div className="text-xs text-slate-300 border-t border-slate-100 pt-4 leading-relaxed">
            Data: Adzuna live job listings · Numbeo cost-of-living · IRCC Express Entry · UK Home Office ·
            Australian Dept. of Home Affairs · USCIS · QS Employability Rankings · RBI forex rates.
            Generated by ROI Oracle — Leap AI Hackathon 2026.
          </div>
        </div>
      </div>

      {/* Action buttons */}
      <div className="flex gap-2.5 flex-wrap">
        <button
          onClick={downloadPDF}
          disabled={pdfLoading}
          className="btn-primary text-xs px-4 py-2.5 gap-1.5 flex-1 justify-center"
        >
          {pdfLoading
            ? <><Loader2 size={13} className="animate-spin" />Generating PDF…</>
            : <><Download size={13} />Download PDF</>
          }
        </button>

        <button onClick={shareWhatsApp} className="btn-green text-xs px-4 py-2.5 gap-1.5 flex-1 justify-center">
          <Share2 size={13} />Share on WhatsApp
        </button>

        <button onClick={onBack} className="btn-outline text-xs px-4 py-2.5 gap-1.5">
          <ChevronLeft size={13} />Dashboard
        </button>
      </div>

      {/* CTA */}
      <div className="bg-navy-900 rounded-2xl p-5 relative overflow-hidden">
        <div className="absolute top-0 right-0 w-28 h-28 bg-brand-orange/20 rounded-full -translate-y-1/2 translate-x-1/2" />
        <div className="relative z-10">
          <div className="text-sm font-extrabold text-white mb-1.5">Ready to take the next step?</div>
          <div className="text-xs text-white/55 leading-relaxed mb-3.5">
            Your Leap Scholar counselor can lock in your application, apply for a LeapFinance loan, and book IELTS prep — all in one free session.
          </div>
          <button
            onClick={() => toast.success('Counselor booking — production feature')}
            className="btn-orange text-xs py-2 gap-1.5"
          >
            Book free counselor session <ArrowRight size={13} />
          </button>
        </div>
      </div>
    </div>
  )
}
